/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

public class FindTheDifference {
  public static void main(String[] args) {
    System.out.println(findTheDifference("abcd", "abcde"));
    System.out.println(findTheDifference("", "y"));
  }

  public static char findTheDifference(String s, String t) {
    int[] letters = new int[26];
    for (int i = 0; i < s.length(); i++) {
      letters[s.charAt(i) - 'a']++;
    }
    for (int i = 0; i < t.length(); i++) {
      if (--letters[t.charAt(i) - 'a'] < 0) {
        return t.charAt(i);
      }
    }
    return ' ';
  }
}
